name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master # Change this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token "1//098Moy8gM6TQSCgYIARAAGAkSNwF-L9IrgYq01V9HAK-l0_CV1SgUV7D_PdtigNlQjjHEdmp8BeZywHJkO1ErLpV2Pyf0S1CrpX4"
